spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/zyls-wms-test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
server:
  port: 8081
