spring:
  redis:
    database: 2
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: 10ms
    timeout: 1000ms
    max-active: 20
    max-wait: 10ms
