spring:
  application:
    name: hello-service
eureka:
  client:
    serviceUrl:
#      defaultZone: http://peer2:2223/eureka/,http://peer1:2222/eureka/
      defaultZone: http://localhost:1111/eureka/
    healthcheck:
      enabled: true
server:
  port: 8080

