server:
  port: 9001
spring:
  application:
    name: user-register-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl.defaultZone: http://localhost:9002/eureka/
    healthcheck:
      enabled: true
